sonar.projectKey=Dianamar06_Proyecto-Mejora-SJR
sonar.projectName=Mejora SJR
sonar.sourceEncoding=UTF-8

sonar.sources=mejora-sjr-backend/src,mejora-sjr-admin/src,mejora-sjr-mobile/src
sonar.tests=mejora-sjr-backend/tests,mejora-sjr-mobile/tests
sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/dist/**,**/build/**,**/package-lock.json
